export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const DECREMENT_CART_ITEM_QUANTITY = 'DECREMENT_CART_ITEM_QUANTITY';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const CLEAR_CART_ITEMS = 'CLEAR_CART_ITEMS';
export const CLEAR_CART_ITEMS_LOCAL = 'CLEAR_CART_ITEMS_LOCAL';
export const PURCHASE = 'PURCHASE';
export const SET_SUCCESS_BUY_TO_FALSE = 'SET_SUCCESS_BUY_TO_FALSE';
