export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const DECREMENT_CART_ITEM_QUANTITY = 'DECREMENT_CART_ITEM_QUANTITY';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
